### ISSUE TITLE
tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by RSteendam** [masashi-y/depccg#30]
I could not get depccg to work. I first tried installing via pip, then I cloned the repo and  tried:
```
pip install -U cython
python setup.py clean
python setup.py build_ext --inplace
python setup.py install  
```

However, in both cases, running the `depccg_en download` then gives:
```
  warnings.warn('''\
2022-06-01 10:34:05,848 - INFO - root - start downloading from 1mxl1HU99iEQcUYhWhvkowbE4WOH0UKxv
Downloading 1mxl1HU99iEQcUYhWhvkowbE4WOH0UKxv into /Users/ruben/github/depccg/depccg/models/tri_headfirst.tar.gz... Done.
2022-06-01 10:34:06,273 - INFO - root - extracting files
Traceback (most recent call last):
  File "/Users/ruben/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/ruben/.pyenv/versions/3.8.13/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ruben/github/depccg/depccg/__main__.py", line 166, in <module>
    parse_args(main)
  File "/Users/ruben/github/depccg/depccg/argparse.py", line 203, in parse_args
    args.func(args)
  File "/Users/ruben/github/depccg/depccg/argparse.py", line 112, in <lambda>
    func=lambda args: download(args.lang, args.VARIANT)
  File "/Users/ruben/github/depccg/depccg/instance_models.py", line 108, in download
    tf = tarfile.open(filename)
  File "/Users/ruben/.pyenv/versions/3.8.13/lib/python3.8/tarfile.py", line 1608, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

MBP Pro 2021 (M1 Pro), macOS 12.4
python3.8.13
numpy==1.22.4
Cython==0.29.30
Clang:
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0

**Comment by RSteendam** [comment]
`tri_headfirst.tar.gz` is only a 2KB file.

**Comment by RSteendam** [comment]
Manually downloading and extracting the archive fixed this issue.

**Comment by masashi-y** [comment]
Resolved in depccg 3.0.0 by the updated Google Drive downloader and model-cache handling. Current English basic-model download and inference were verified from a clean cache during the 3.0.0 release and are covered by scheduled smoke tests. This overlaps #36; please open a new issue with current-version logs if it recurs.
