### ISSUE TITLE
tri_headfirst.tar.gz downloads as an HTML file, not a .tar.gz file

### ISSUE THREAD

**Issue by axb21** [masashi-y/depccg#36]
Following the install instructions, I executed `depccg_en download`. This is what happened:
```bash
username@localhost:~$ depccg_en download
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
2022-11-02 10:39:13,164 - INFO - root - start downloading from 1mxl1HU99iEQcUYhWhvkowbE4WOH0UKxv
Downloading 1mxl1HU99iEQcUYhWhvkowbE4WOH0UKxv into /home/username/.local/lib/python3.10/site-packages/depccg/models/tri_headfirst.tar.gz... Done.
2022-11-02 10:39:13,535 - INFO - root - extracting files
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/username/.local/lib/python3.10/site-packages/depccg/__main__.py", line 166, in <module>
    parse_args(main)
  File "/home/username/.local/lib/python3.10/site-packages/depccg/argparse.py", line 203, in parse_args
    args.func(args)
  File "/home/username/.local/lib/python3.10/site-packages/depccg/argparse.py", line 112, in <lambda>
    func=lambda args: download(args.lang, args.VARIANT)
  File "/home/username/.local/lib/python3.10/site-packages/depccg/instance_models.py", line 108, in download
    tf = tarfile.open(filename)
  File "/usr/lib/python3.10/tarfile.py", line 1639, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('invalid header')
```

The error seems to be telling me that `tri_headfirst.tar.gz` is not the expected file type. Checking it with `file`:
```bash
username@localhost:~$ file /home/username/.local/lib/python3.10/site-packages/depccg/models/tri_headfirst.tar.gz
/home/username/.local/lib/python3.10/site-packages/depccg/models/tri_headfirst.tar.gz: HTML document, ASCII text, with very long lines (2035)
```

The contents of the file, if it helps:
```html
<!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="C7JrQ_bxZ2npIv_xsTlBUg">/* Copyright 2022 Google Inc. All Rights Reserved. */
.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}</style><link rel="icon" href="null"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for viruses.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="/open?id=1mxl1HU99iEQcUYhWhvkowbE4WOH0UKxv">tri_headfirst.tar.gz</a> (189M)</span> is too large for Google to scan for viruses. Would you still like to download this file?</p><form id="downloadForm" action="https://docs.google.com/uc?export=download&amp;id=1mxl1HU99iEQcUYhWhvkowbE4WOH0UKxv&amp;confirm=t&amp;uuid=02449c1a-bdbb-40bb-b114-d77c9c61b6ea" method="post"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
```

Net result is that the installation procedures don't work in my environment as written, and it would seem they wouldn't work for anyone else either?

If I'm reading the HTML contents right it appears this code is trying to download `tri_headfirst.tar.gz` from Google Drive, which is not great if true.

**Comment by DavidDemitriAfrica** [comment]
To fix this, you can wget from the final redirected link (after clicking download manually)

`!wget --no-check-certificate \
  "https://drive.usercontent.google.com/download?id=1mxl1HU99iEQcUYhWhvkowbE4WOH0UKxv&authuser=1&confirm=t&uuid=00d62ce5-3557-48c1-84c5-a288f9767b82&at=APvzH3qYc5s6Pr8DlOP1ylUWJxoJ%3A1735014465910" \
  -O tri_headfirst.tar.gz`

and manually untar it and move it to the models folder.

`!conda run -n depccg tar xfz tri_headfirst.tar.gz \
    -C /usr/local/envs/depccg/lib/python3.8/site-packages/depccg/models`

But I'm not sure how long-lived the link will be, so this is probably not a good fix.

**Comment by masashi-y** [comment]
Resolved in depccg 3.0.0. Model downloads now handle Google Drive downloads correctly, store models in the user cache, and reject invalid or unsafe archives. The English basic-model download and inference path is exercised by scheduled CI and was verified again for the 3.0.0 release. Please open a new issue if the current `depccg_en download` command fails.
