### ISSUE TITLE
Chainer version error

### ISSUE THREAD

**Issue by haur21** [masashi-y/depccg#38]
I installed the Japanese version of depccg. There were no errors during the installation. However, when I try to run it, I encounter the following error. Could you tell me whether this issue is related to my computer's environment or if it is a problem with the version of Chainer?

 echo "これはテストの文です。" | depccg_ja -f deriv
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/haruna/sample/lib/python3.10/site-packages/depccg/__main__.py", line 7, in <module>
    from depccg.printer import print_
  File "/home/haruna/sample/lib/python3.10/site-packages/depccg/printer/__init__.py", line 8, in <module>
    from depccg.instance_models import SEMANTIC_TEMPLATES
  File "/home/haruna/sample/lib/python3.10/site-packages/depccg/instance_models.py", line 8, in <module>
    from depccg.chainer.supertagger import load_chainer_tagger
  File "/home/haruna/sample/lib/python3.10/site-packages/depccg/chainer/supertagger.py", line 7, in <module>
    from depccg.chainer.lstm_parser_bi_fast import FastBiaffineLSTMParser
  File "/home/haruna/sample/lib/python3.10/site-packages/depccg/chainer/lstm_parser_bi_fast.py", line 5, in <module>
    import chainer.links as L
ModuleNotFoundError: No module named 'chainer.links'

**Comment by masashi-y** [comment]
This is resolved in depccg 3.0.0. The Chainer runtime was replaced with PyTorch, and the Japanese pretrained parser now supports Python 3.10–3.14. The reported command can be run after installing the current release and downloading the model:

```sh
pip install -U depccg
depccg_ja download
echo "これはテストの文です。" | depccg_ja --format deriv
```

Please open a new issue with current-version details if a problem remains.
